// Code generated by github.com/noxproject/nox/tools/ngen. DO NOT EDIT.

package types

import (
	"encoding/json"
)

var _ = (*genesisJSON)(nil)

// MarshalJSON marshals as JSON
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config *Config
		Nonce  UInt64
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Nonce = UInt64(g.Nonce)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON
func (g *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Config *Config
		Nonce  *UInt64
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		g.Config = dec.Config
	}
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	return nil
}
