language: go

go:
  - "1.12.x"

sudo: false

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

env:
  - GO111MODULE=on

script:
  - ./ci.sh