// Code generated by qitmeer/tools/ngen. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
)

var _ = (*genesisJSON)(nil)

// MarshalJSON marshals as JSON
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Config *Config `json:"config" required:"true"`
		Nonce  UInt64  `json:"nonce"  required:"true" min:"1"`
	}
	var enc Genesis
	enc.Config = g.Config
	enc.Nonce = UInt64(g.Nonce)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON
func (g *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Config *Config `json:"config" required:"true"`
		Nonce  *UInt64 `json:"nonce"  required:"true" min:"1"`
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config == nil {
		return errors.New("missing required field 'config' for Genesis")
	}
	g.Config = dec.Config
	if dec.Nonce == nil {
		return errors.New("missing required field 'nonce' for Genesis")
	}
	g.Nonce = uint64(*dec.Nonce)
	if g.Nonce < 1 {
		return errors.New("error field 'nonce' for Genesis, minimal is 1")
	}
	return nil
}
