name: GoTest

on:
  push:
    branches: [ master,0.10-dev,0.10.6-mixnet ]
  pull_request:
    branches: [ master,0.10-dev,0.10.6-mixnet ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 
        with:
          go-version: 1.16

      - name: linter
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

      - name: Build
        run: make qitmeer

      - name: Test
        run: |
          PATH=$PATH:$(pwd)/build/bin
          go test -v ./...
      
      - name: Run ci.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: ./ci.sh
